### ISSUE TITLE
[Request] Exclude files

### ISSUE THREAD

**Issue by rmscode** [tombreit/mkdocs-git-latest-changes-plugin#12]
I know nothing about Python or else I would try to contribute to this project, but I think it would be useful to be able to exclude certain files/paths from the generated list of recent changes. 

Example:

```yml
# mkdocs.yml plugin configuration example
    plugins:
      - git-latest-changes:
          limit_to_docs_dir: True  # [True|False], defaults to False
          repo_vendor: gitea  # [github|gitlab|gitea], defaults to `repo_name`
          enabled_on_serve: True  # [True|False], defaults to True
          exclude: # list of files/paths to exclude from generated list of recent changes, defaults to none
            - index.md
            - notes/*
```

ChatGPT suggested this:

```py
from pydantic import BaseModel, fields

class GitLatestChangesPluginConfig(BaseModel):
    limit_to_docs_dir: bool = False
    repo_vendor: str = 'repo_name'
    enabled_on_serve: bool = True
    exclude: fields.List[str] = []
```
