### ISSUE TITLE
[Request] Define history length

### ISSUE THREAD

**Issue by rmscode** [tombreit/mkdocs-git-latest-changes-plugin#13]
I think it would be a nice addition to this project to be able to define how much history the plugin generates. Something like 7 days, 30 days, or ALL.

Example:

```yml
# mkdocs.yml plugin configuration example
    plugins:
      - git-latest-changes:
          limit_to_docs_dir: True  # [True|False], defaults to False
          repo_vendor: gitea  # [github|gitlab|gitea], defaults to `repo_name`
          enabled_on_serve: True  # [True|False], defaults to True
          show_x_days: 7 # [-1(ALL)|7|30] Generates only the last x days of recent history, defaults to ALL
```

**Comment by tombreit** [comment]
This topic has already been addressed in [issue 3](https://github.com/tombreit/mkdocs-git-latest-changes-plugin/issues/3). Personally, I prefer the simple solution mentioned there with “N commit messages”, without (relative) time specifications.

**Comment by tombreit** [comment]
> Understood! Sorry I missed that!

No problem. Would something like #3 suit your needs?

**Comment by rmscode** [comment]
It would. Thank you.

**Comment by tombreit** [comment]
If you would like to try it out:

Set your history limit via

```yml
    plugins:
      - git-latest-changes:
          history_limit: 5  # [Integer, defaults to -1 (no history limit)]
```

```bash
$ pip install git+https://github.com/tombreit/mkdocs-pagetree-plugin.git@e43a5632eaa511eb2fe54c9a326fc29e9a9f5d03
```
