### ISSUE TITLE
TypeError on gitlab instance

### ISSUE THREAD

**Issue by maba2402** [tombreit/mkdocs-git-latest-changes-plugin#15]
The plugin is not working if executed by a gitlab runner. It crashes with the following exception:

`ERROR   -  An exception of type TypeError occurred. Arguments:
("HEAD is a detached symbolic reference as it points to '26a5edb2cdae0a1b02f701cd6b2bc6cf5ef0cbff'",)`

The problem can be traced back to the method get_recent_changes.

```
def get_recent_changes(
    *, repo_url: str, repo_vendor: str, limit_to_docs_dir: str, history_limit: int
) -> str:
    try:
        repo = Repo()
        branch = repo.active_branch
        git = repo.git
```

The line 
`  branch = repo.active_branch`
raises the exception.

The problem is that in my case gitlab does not checkout a branch but works rather on a defined commit.

```
$ git branch
(HEAD detached at 26a5edb)

$ git rev-parse --abbrev-ref HEAD
HEAD
```

This problem has been discussed here [#633](https://github.com/gitpython-developers/GitPython/issues/633)

**Comment by tombreit** [comment]
Hi @maba2402 , 

could you please post your `.gitlab-ci.yml`?

**Comment by tombreit** [comment]
Without knowing your configuration, I can only speculate:

* https://docs.gitlab.com/ee/user/project/repository/monorepos/index.html#shallow-cloning
* https://docs.gitlab.com/ee/ci/pipelines/settings.html#limit-the-number-of-changes-fetched-during-clone

Example (pseudocode):

```yml
# .gitlab-ci.yml

variables:
  GIT_DEPTH: 0
```

**Comment by maba2402** [comment]
I looked a bit more into the details of my .gitlab-ci.yml and tried your proposal. Unfortunately, the situation is still the same.  Here are the details.

```
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
    GIT_DEPTH: 0

build-mkdocs:
  stage: test
  script:
    - poetry run mkdocs build ${CI_MERGE_REQUEST_IID+--no-directory-urls}
  artifacts:
    expire_in: 3h
    paths:
      - site/
  tags:
    - DOCKER
```

**Comment by tombreit** [comment]
Perhaps you could force a `git pull` of your branch?:

```yml
# .gitlab-ci.yml

variables:
  GIT_DEPTH: 0

build-mkdocs:
  stage: test
  script:
    - git pull origin <insertyourbranch>
    - git switch <insertyourbranch>
    - git pull
    - poetry run mkdocs build ${CI_MERGE_REQUEST_IID+--no-directory-urls}
```

**Comment by maba2402** [comment]
Thanks a lot. That works.

**Comment by maba2402** [comment]
Unfortunately, the proposed solution does not work with a Merge-Request based approach. I need to further investigate this issue.

**Comment by tombreit** [comment]
It would be nice if you could detail the steps that lead to this error here.

**Comment by mfominov** [comment]
Faced same issue.
Found an a solution https://stackoverflow.com/a/77006148/11857414

**Comment by tombreit** [comment]
Thanks @mfominov , I will now close this (for now) with a recap of your tip.

```yml
job:
  script:
    - git switch $CI_COMMIT_REF_NAME #returning to branch from detached HEAD
    - <your CI script>
  variables:
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
```

GIT_STRATEGY:
https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy

GIT_DEPTH:
https://docs.gitlab.com/ee/ci/runners/configure_runners.html#shallow-cloning

**Comment by artpelling** [comment]
Facing the same issue, this should be stated more prominently in the docs of this plugin IMO

**Comment by tombreit** [comment]
Hi @artpelling , 

would have helped to add this to the *Hints* section of the docs?:

---
- Usage in a CI environment (e.g. Gitlab) may need some tweaking:
    - GitLab `.gitlab-ci.yml`:

        ```yml
        job:
          script:
            - git switch $CI_COMMIT_REF_NAME  # Returning to branch from detached HEAD
            - <your CI script>
          variables:
            # https://docs.gitlab.com/ee/ci/runners/configure_runners.html#shallow-cloning
            GIT_DEPTH: 0
            # https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy
            GIT_STRATEGY: clone
        ```
---

You are welcome to improve or correct this part.
