### ISSUE TITLE
feat request: Option to link to rendered/hosted page instead of git-repo file

### ISSUE THREAD

**Issue by tuxuser** [tombreit/mkdocs-git-latest-changes-plugin#18]
Hi

Very happy this plugin exists!
It would be nice to have a configuration option to link each file-entry in recent-changes to the rendered / hosted file instead of the git file.

Something like introducing the option

```yaml
  link_to_generated_page: True | False
```

It requires `config.site_url` and `limit_to_docs_dir: True` to be set, to be able to assemble the final uri and actually link to the rendered page. If criteria is not met, checked in `on_config`, a `PluginError` is raised.

Also, the `Files` that's passed to `on_page_markdown()` needs to be passed around, to be able to map source -> destination filepath/uri.

The `on_files` event was added to filter out generated files to not cause problems when mapping paths.

Here is an attempt at implementing this, tests included.

As this is my first attempt at a mkdocs plugin, I am sure you have some best-practices to recommend :)

https://github.com/tuxuser/mkdocs-git-latest-changes-plugin/commit/292fa653ca39323e8a6c31d831335f7b393a5d7c

You can see the result of this option here: <https://xboxoneresearch.github.io/wiki/recent-changes/index.html>

Update: Continued in PR #19

**Comment by tombreit** [comment]
Hi @tuxuser , 

first draft: https://github.com/tombreit/mkdocs-git-latest-changes-plugin/tree/feature-link-rendered-pages

No tests yet, not even thoroughly tested by myself - but it should be possible to render "your table": 

```yaml
plugins:
  - git-latest-changes:
      limit_to_docs_dir: True
      repo_vendor: github
      enabled_on_serve: True
      history_limit: -1
      timestamp_format: "%Y"
      changelog_features:
        - "page_link_rendered"
        - "timestamp"
        - "author"
        - "message"
        - "commit_hash_link"
```

You could even set `limit_to_docs_dir: False` and you should get linked rendered pages and not linked files.

The "changelog_features" define the columns and their ordering.

The usecase for me would be to "configure" a recent changes table that addresses a non-technical audience, e.g.:

```yaml
      limit_to_docs_dir: True
      timestamp_format: "%c"
      changelog_features:
        - "page_link_rendered"
        - "timestamp"
        - "author"
        - "message"
```

...the current sorting of the entries is not yet correct.
